services:
- type: web
  name: api-lang-media
  runtime: node
  rootDir: apps/backend
  buildCommand: npm install --package-lock-only; npm ci; npm build --omit=dev;
  plan: free
  region: singapore
  startCommand: npm start backend
  envVars:
    - key: NX_DB_HOST
      sync: false
    - key: NX_DB_DIALECT
      sync: false
    - key: NX_DB_USERNAME
      sync: false
    - key: NX_DB_PASSWORD
      sync: false
    - key: NX_DB_NAME
      sync: false
    - key: NX_NODE_ENV
      sync: false
    - key: NX_CACHE_TTL
      sync: false
    - key: NX_CACHE_DRIVER
      sync: false
    - key: NX_GRAPHQL_CACHE_MAX_AGE
      sync: false
    - key: NX_HASH_NUMBER
      sync: false
    - key: NX_JWT_SECRET
      sync: false
    - key: NX_JWT_EXPIRATION_TIME
      sync: false
- type: web
  name: lang-media
  runtime: node
  rootDir: apps/frontend
  buildCommand: npm install --package-lock-only; npm ci; npm build --omit=dev;
  plan: free
  region: singapore
  startCommand: npm start frontend
- type: web
  name: lang-media-admin
  runtime: node
  rootDir: apps/frontend-admin
  buildCommand: npm install --package-lock-only; npm ci; npm build --omit=dev;
  plan: free
  region: singapore
  startCommand: npm start frontend-admin