name: Node.js CI

on:
  push:
    branches: [ "dev/features" ]
  pull_request:
    branches: [ "dev/features" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm install --legacy-peer-deps
    - run: npm test
    - run: docker-compose up
